version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test_topic:1.1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
#  rest-proxy:
#    image: confluentinc/cp-kafka-rest:5.1.2
#    depends_on:
#      - zookeeper
#      - kafka
#      # - schema-registry
#    ports:
#      - 18082:8082
#    hostname: rest-proxy
#    container_name: rest-proxy
#    environment:
#      KAFKA_REST_HOST_NAME: rest-proxy
#      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:29092'
#      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
#      # KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
#  topics-ui:
#    image: landoop/kafka-topics-ui
#    depends_on:
#      - rest-proxy
#    ports:
#      - 18000:8000
#    environment:
#      - KAFKA_REST_PROXY_URL=http://rest-proxy:18082
#      - PROXY=true